# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{twitpic4r}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Keishi Hosoba"]
  s.date = %q{2010-07-21}
  s.description = %q{twitpic API wrapper for ruby}
  s.email = %q{tech.hosopy@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/twitpic/base.rb",
     "lib/twitpic/helper.rb",
     "lib/twitpic/oauth.rb",
     "lib/twitpic/twitpic.rb",
     "lib/twitpic4r.rb",
     "sample/main.rb",
     "sample/test.gif",
     "sample/test.jpg",
     "sample/test.png",
     "test/helper.rb",
     "test/test_twitpic4r.rb"
  ]
  s.homepage = %q{http://github.com/hosopy/twitpic4r}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{twitpic API wrapper for ruby}
  s.test_files = [
    "test/helper.rb",
     "test/test_twitpic4r.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

